# Generated by Django 3.2.7 on 2021-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0003_auto_20211010_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id_country',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id_race',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id_type',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id_user',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_identification_type',
            field=models.IntegerField(max_length=10),
        ),
    ]
