# Generated by Django 3.2.7 on 2021-10-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_mascotas', '0005_alter_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
        migrations.DeleteModel(
            name='identification_type',
        ),
        migrations.DeleteModel(
            name='pet',
        ),
        migrations.DeleteModel(
            name='race',
        ),
        migrations.DeleteModel(
            name='session',
        ),
        migrations.DeleteModel(
            name='type',
        ),
    ]
